// Code generated by dagger-compiler.  Do not edit.
package org.anotanota;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<AggregatedProductsViewController>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code AggregatedProductsViewController} and its
 * dependencies.
 *
 * Being a {@code Provider<AggregatedProductsViewController>} and handling creation and
 * preparation of object instances.
 */
public final class AggregatedProductsViewController$$InjectAdapter extends Binding<AggregatedProductsViewController>
    implements Provider<AggregatedProductsViewController> {
  private Binding<android.support.v7.app.ActionBar> actionBar;

  public AggregatedProductsViewController$$InjectAdapter() {
    super("org.anotanota.AggregatedProductsViewController", "members/org.anotanota.AggregatedProductsViewController", NOT_SINGLETON, AggregatedProductsViewController.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    actionBar = (Binding<android.support.v7.app.ActionBar>) linker.requestBinding("android.support.v7.app.ActionBar", AggregatedProductsViewController.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(actionBar);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<AggregatedProductsViewController>}.
   */
  @Override
  public AggregatedProductsViewController get() {
    AggregatedProductsViewController result = new AggregatedProductsViewController(actionBar.get());
    return result;
  }

}
