// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.framework;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<Activity.ActivityModules>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code Activity.ActivityModules} and its
 * dependencies.
 *
 * Being a {@code Provider<Activity.ActivityModules>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<Activity.ActivityModules>} and handling injection
 * of annotated fields.
 */
public final class Activity$ActivityModules$$InjectAdapter extends Binding<Activity.ActivityModules>
    implements Provider<Activity.ActivityModules>, MembersInjector<Activity.ActivityModules> {
  private Binding<Object[]> mActivityModules;

  public Activity$ActivityModules$$InjectAdapter() {
    super("org.anotanota.framework.Activity$ActivityModules", "members/org.anotanota.framework.Activity$ActivityModules", NOT_SINGLETON, Activity.ActivityModules.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    mActivityModules = (Binding<Object[]>) linker.requestBinding("@org.anotanota.framework.App$ActivityModules()/java.lang.Object[]", Activity.ActivityModules.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(mActivityModules);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<Activity.ActivityModules>}.
   */
  @Override
  public Activity.ActivityModules get() {
    Activity.ActivityModules result = new Activity.ActivityModules();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<Activity.ActivityModules>}.
   */
  @Override
  public void injectMembers(Activity.ActivityModules object) {
    object.mActivityModules = mActivityModules.get();
  }

}
