// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.framework.pager;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<PagerAdapter>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code PagerAdapter} and its
 * dependencies.
 *
 * Being a {@code Provider<PagerAdapter>} and handling creation and
 * preparation of object instances.
 */
public final class PagerAdapter$$InjectAdapter extends Binding<PagerAdapter>
    implements Provider<PagerAdapter> {
  private Binding<android.support.v4.app.FragmentManager> fm;
  private Binding<java.util.List<String>> pagerTitles;
  private Binding<Provider<org.anotanota.framework.UIViewController>> viewController;

  public PagerAdapter$$InjectAdapter() {
    super("org.anotanota.framework.pager.PagerAdapter", "members/org.anotanota.framework.pager.PagerAdapter", IS_SINGLETON, PagerAdapter.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    fm = (Binding<android.support.v4.app.FragmentManager>) linker.requestBinding("android.support.v4.app.FragmentManager", PagerAdapter.class, getClass().getClassLoader());
    pagerTitles = (Binding<java.util.List<String>>) linker.requestBinding("@org.anotanota.framework.pager.Pager$Titles()/java.util.List<java.lang.String>", PagerAdapter.class, getClass().getClassLoader());
    viewController = (Binding<Provider<org.anotanota.framework.UIViewController>>) linker.requestBinding("@org.anotanota.framework.pager.Pager$Tabs()/javax.inject.Provider<org.anotanota.framework.UIViewController>", PagerAdapter.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(fm);
    getBindings.add(pagerTitles);
    getBindings.add(viewController);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<PagerAdapter>}.
   */
  @Override
  public PagerAdapter get() {
    PagerAdapter result = new PagerAdapter(fm.get(), pagerTitles.get(), viewController.get());
    return result;
  }

}
