// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.account;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AccountModule$$ModuleAdapter extends ModuleAdapter<AccountModule> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public AccountModule$$ModuleAdapter() {
    super(org.anotanota.account.AccountModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  @Override
  public AccountModule newModule() {
    return new org.anotanota.account.AccountModule();
  }
}
