// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.pipeline;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AnotanotaPipelineModule$$ModuleAdapter extends ModuleAdapter<AnotanotaPipelineModule> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public AnotanotaPipelineModule$$ModuleAdapter() {
    super(org.anotanota.pipeline.AnotanotaPipelineModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  @Override
  public AnotanotaPipelineModule newModule() {
    return new org.anotanota.pipeline.AnotanotaPipelineModule();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, AnotanotaPipelineModule module) {
    bindings.contributeProvidesBinding("@org.anotanota.pipeline.AnotanotaPipeline$FullPipeline()/java.lang.Object[]", new GetProducersProvidesAdapter(module));
    bindings.contributeProvidesBinding("@org.anotanota.pipeline.AnotanotaPipeline$ItemsFromString()/java.lang.Object[]", new GetProducersItemsFromStringProvidesAdapter(module));
  }

  /**
   * A {@code Binding<java.lang.Object[]>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<java.lang.Object[]>} and handling creation and
   * preparation of object instances.
   */
  public static final class GetProducersProvidesAdapter extends ProvidesBinding<Object[]>
      implements Provider<Object[]> {
    private final AnotanotaPipelineModule module;

    public GetProducersProvidesAdapter(AnotanotaPipelineModule module) {
      super("@org.anotanota.pipeline.AnotanotaPipeline$FullPipeline()/java.lang.Object[]", NOT_SINGLETON, "org.anotanota.pipeline.AnotanotaPipelineModule", "getProducers");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<java.lang.Object[]>}.
     */
    @Override
    public Object[] get() {
      return module.getProducers();
    }
  }

  /**
   * A {@code Binding<java.lang.Object[]>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<java.lang.Object[]>} and handling creation and
   * preparation of object instances.
   */
  public static final class GetProducersItemsFromStringProvidesAdapter extends ProvidesBinding<Object[]>
      implements Provider<Object[]> {
    private final AnotanotaPipelineModule module;

    public GetProducersItemsFromStringProvidesAdapter(AnotanotaPipelineModule module) {
      super("@org.anotanota.pipeline.AnotanotaPipeline$ItemsFromString()/java.lang.Object[]", NOT_SINGLETON, "org.anotanota.pipeline.AnotanotaPipelineModule", "getProducersItemsFromString");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<java.lang.Object[]>}.
     */
    @Override
    public Object[] get() {
      return module.getProducersItemsFromString();
    }
  }
}
