// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.pipeline;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class InputReceiptProducer$$ModuleAdapter extends ModuleAdapter<InputReceiptProducer> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public InputReceiptProducer$$ModuleAdapter() {
    super(org.anotanota.pipeline.InputReceiptProducer.class, INJECTS, STATIC_INJECTIONS, true /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, InputReceiptProducer module) {
    bindings.contributeProvidesBinding("org.anotanota.model.Receipt", new GetReceiptProvidesAdapter(module));
  }

  /**
   * A {@code Binding<org.anotanota.model.Receipt>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<org.anotanota.model.Receipt>} and handling creation and
   * preparation of object instances.
   */
  public static final class GetReceiptProvidesAdapter extends ProvidesBinding<org.anotanota.model.Receipt>
      implements Provider<org.anotanota.model.Receipt> {
    private final InputReceiptProducer module;

    public GetReceiptProvidesAdapter(InputReceiptProducer module) {
      super("org.anotanota.model.Receipt", NOT_SINGLETON, "org.anotanota.pipeline.InputReceiptProducer", "getReceipt");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<org.anotanota.model.Receipt>}.
     */
    @Override
    public org.anotanota.model.Receipt get() {
      return module.getReceipt();
    }
  }
}
