// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.pipeline;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class InputFileProducer$$ModuleAdapter extends ModuleAdapter<InputFileProducer> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public InputFileProducer$$ModuleAdapter() {
    super(org.anotanota.pipeline.InputFileProducer.class, INJECTS, STATIC_INJECTIONS, true /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, InputFileProducer module) {
    bindings.contributeProvidesBinding("java.io.File", new GetInputFileProvidesAdapter(module));
  }

  /**
   * A {@code Binding<java.io.File>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<java.io.File>} and handling creation and
   * preparation of object instances.
   */
  public static final class GetInputFileProvidesAdapter extends ProvidesBinding<java.io.File>
      implements Provider<java.io.File> {
    private final InputFileProducer module;

    public GetInputFileProvidesAdapter(InputFileProducer module) {
      super("java.io.File", NOT_SINGLETON, "org.anotanota.pipeline.InputFileProducer", "getInputFile");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<java.io.File>}.
     */
    @Override
    public java.io.File get() {
      return module.getInputFile();
    }
  }
}
