// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.pipeline;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class ProductsProducer$$ModuleAdapter extends ModuleAdapter<ProductsProducer> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public ProductsProducer$$ModuleAdapter() {
    super(org.anotanota.pipeline.ProductsProducer.class, INJECTS, STATIC_INJECTIONS, true /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  @Override
  public ProductsProducer newModule() {
    return new org.anotanota.pipeline.ProductsProducer();
  }
}
