// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.pipeline;

import dagger.internal.Binding;
import dagger.internal.BindingsGroup;
import dagger.internal.Linker;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import java.util.Set;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class ReceiptItemsProducer$$ModuleAdapter extends ModuleAdapter<ReceiptItemsProducer> {
  private static final String[] INJECTS = { "members/org.anotanota.model.ReceiptItem", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { org.anotanota.pipeline.ReceiptItemsProducer.Inputs.class, };

  public ReceiptItemsProducer$$ModuleAdapter() {
    super(org.anotanota.pipeline.ReceiptItemsProducer.class, INJECTS, STATIC_INJECTIONS, true /*overrides*/, INCLUDES, true /*complete*/, true /*library*/);
  }

  @Override
  public ReceiptItemsProducer newModule() {
    return new org.anotanota.pipeline.ReceiptItemsProducer();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, ReceiptItemsProducer module) {
    bindings.contributeProvidesBinding("org.anotanota.model.ReceiptItem", new GetReceiptItemsProvidesAdapter(module));
  }

  /**
   * A {@code Binding<org.anotanota.model.ReceiptItem>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Owning the dependency links between {@code org.anotanota.model.ReceiptItem} and its
   * dependencies.
   *
   * Being a {@code Provider<org.anotanota.model.ReceiptItem>} and handling creation and
   * preparation of object instances.
   */
  public static final class GetReceiptItemsProvidesAdapter extends ProvidesBinding<org.anotanota.model.ReceiptItem>
      implements Provider<org.anotanota.model.ReceiptItem> {
    private final ReceiptItemsProducer module;
    private Binding<org.anotanota.model.Receipt> receipt;
    private Binding<org.anotanota.model.ReceiptItemsDataAccess> itemsDA;

    public GetReceiptItemsProvidesAdapter(ReceiptItemsProducer module) {
      super("org.anotanota.model.ReceiptItem", NOT_SINGLETON, "org.anotanota.pipeline.ReceiptItemsProducer", "getReceiptItems");
      this.module = module;
      setLibrary(true);
    }

    /**
     * Used internally to link bindings/providers together at run time
     * according to their dependency graph.
     */
    @Override
    @SuppressWarnings("unchecked")
    public void attach(Linker linker) {
      receipt = (Binding<org.anotanota.model.Receipt>) linker.requestBinding("org.anotanota.model.Receipt", ReceiptItemsProducer.class, getClass().getClassLoader());
      itemsDA = (Binding<org.anotanota.model.ReceiptItemsDataAccess>) linker.requestBinding("org.anotanota.model.ReceiptItemsDataAccess", ReceiptItemsProducer.class, getClass().getClassLoader());
    }

    /**
     * Used internally obtain dependency information, such as for cyclical
     * graph detection.
     */
    @Override
    public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
      getBindings.add(receipt);
      getBindings.add(itemsDA);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<org.anotanota.model.ReceiptItem>}.
     */
    @Override
    public org.anotanota.model.ReceiptItem get() {
      return module.getReceiptItems(receipt.get(), itemsDA.get());
    }
  }
}
