// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.sqlite;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<SQLiteReceiptItemsDataAccess>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code SQLiteReceiptItemsDataAccess} and its
 * dependencies.
 *
 * Being a {@code Provider<SQLiteReceiptItemsDataAccess>} and handling creation and
 * preparation of object instances.
 */
public final class SQLiteReceiptItemsDataAccess$$InjectAdapter extends Binding<SQLiteReceiptItemsDataAccess>
    implements Provider<SQLiteReceiptItemsDataAccess> {
  private Binding<android.content.Context> context;
  private Binding<String> dataAccessName;
  private Binding<SQLiteDataAccessConfig> config;

  public SQLiteReceiptItemsDataAccess$$InjectAdapter() {
    super("org.anotanota.sqlite.SQLiteReceiptItemsDataAccess", "members/org.anotanota.sqlite.SQLiteReceiptItemsDataAccess", NOT_SINGLETON, SQLiteReceiptItemsDataAccess.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", SQLiteReceiptItemsDataAccess.class, getClass().getClassLoader());
    dataAccessName = (Binding<String>) linker.requestBinding("@javax.inject.Named(value=DataAccessName)/java.lang.String", SQLiteReceiptItemsDataAccess.class, getClass().getClassLoader());
    config = (Binding<SQLiteDataAccessConfig>) linker.requestBinding("org.anotanota.sqlite.SQLiteDataAccessConfig", SQLiteReceiptItemsDataAccess.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(context);
    getBindings.add(dataAccessName);
    getBindings.add(config);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<SQLiteReceiptItemsDataAccess>}.
   */
  @Override
  public SQLiteReceiptItemsDataAccess get() {
    SQLiteReceiptItemsDataAccess result = new SQLiteReceiptItemsDataAccess(context.get(), dataAccessName.get(), config.get());
    return result;
  }

}
