// Code generated by dagger-compiler.  Do not edit.
package org.anotanota.sqlite;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<SQLiteAggregatedProductsDataAccess>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code SQLiteAggregatedProductsDataAccess} and its
 * dependencies.
 *
 * Being a {@code Provider<SQLiteAggregatedProductsDataAccess>} and handling creation and
 * preparation of object instances.
 */
public final class SQLiteAggregatedProductsDataAccess$$InjectAdapter extends Binding<SQLiteAggregatedProductsDataAccess>
    implements Provider<SQLiteAggregatedProductsDataAccess> {
  private Binding<android.content.Context> context;

  public SQLiteAggregatedProductsDataAccess$$InjectAdapter() {
    super("org.anotanota.sqlite.SQLiteAggregatedProductsDataAccess", "members/org.anotanota.sqlite.SQLiteAggregatedProductsDataAccess", NOT_SINGLETON, SQLiteAggregatedProductsDataAccess.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", SQLiteAggregatedProductsDataAccess.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(context);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<SQLiteAggregatedProductsDataAccess>}.
   */
  @Override
  public SQLiteAggregatedProductsDataAccess get() {
    SQLiteAggregatedProductsDataAccess result = new SQLiteAggregatedProductsDataAccess(context.get());
    return result;
  }

}
